### ISSUE TITLE
Spectrogram from microphone input?

### ISSUE THREAD

**Issue by ipfilip** [Simonwep/spectrum#1]
I'm looking into creating an app for live FFT and I really like your approach.
Could it be possible to use this project as a starting point to make a PWA displaying a live spectrogram?

**Comment by Simonwep** [comment]
That's a pretty cool idea :) I'll look into it ^^

**Comment by Simonwep** [comment]
Added with 1999aec02341e0a0bbcf6429c8177d640ae8d664 :) I'm currently working on a zoom / pan feature and a new UI with preact so stay tuned ^^

**Comment by ipfilip** [comment]
Wow, that was quick for such a major update 😮
